### PR TITLE
OptiFine Cape command

### PR DESCRIPTION
**Pull request by ItsEmpa**
It works, but the bad thing is that if the specified user doesn't have a cape it just doesn't display anything :/

### CODE REVIEW

**Review by toxicscientist — COMMENTED** [review]
This is promising but it'll need to go through testing

**Comment by ItsEmpa** [comment]
Would be so much better if dynamic respones worked on `Post Image` _EHEM COLON, WINK WINK_

**Comment by toxicscientist** [comment]
I don't think Colon reads these

**Comment by ItsEmpa** [comment]
yea ik lol

**Pull request merged**
